### ISSUE TITLE
Feeds extension stopped working

### ISSUE THREAD

**Issue by Danie10** [vector-im/element-integration-manager#101] opened 2023-06-13 18:39 UTC
### Steps to reproduce

1. I installed the new Feeds extension in my room a week back as I had an outdated one. It did work for a day or two.
2. It installed with moderator rights.
3. The RSS feed does work, as I use it elsewhere to populate posts on other sites.
4. Posts just stopped coming through since last Thursday at 14:27.
5. No error messages seen.
6. I've tried deleting and re-adding the RSS feed.
7. I see another person also reported same issue in https://app.element.io/#/room/#element-web:matrix.org.

### Operating system

Manjaro KDE

### Browser information

Brave 153.87

### URL for webapp

https://develop.element.io/

### Homeserver

Matrix.org

### Will you send logs?

No

**Comment by Twi1ightSparkle** [comment] 2023-06-14 09:03
Duplicate of https://github.com/vector-im/element-integration-manager/issues/99

**Closed by Twi1ightSparkle** 2023-06-14 09:03 UTC
Labels: T-Defect
